############################################################################
# BEGIN: BACKOFF RULES
############################################################################
<smtp-pattern-list blocking-errors>
    # Global rules applied to all queues
    reply /421 .* SERVICE NOT AVAILABLE/ mode=backoff
    reply /421 .* Please try again later/ mode=backoff
    reply /Message temporarily deferred/ mode=backoff
    reply /has been temporarily rate limited due to IP reputation/ mode=backoff
    reply /Connection rate limit exceeded/ mode=backoff

    # Treat recipient as hard fail
    reply /OverQuotaTemp/ bounce-rcpt
</smtp-pattern-list>
############################################################################
# END: BACKOFF RULES
############################################################################
